# Generated by Django 5.0.9 on 2024-11-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "webknowledge",
            "0002_usuariosite_rename_idaluno_aluno_qtdaulasassistidas_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aula",
            name="aluno",
        ),
        migrations.AlterField(
            model_name="usuariosite",
            name="cpf",
            field=models.CharField(max_length=11),
        ),
    ]
